cc_library(
  name = "render_graph",
  srcs = ["render_graph.cpp", "render_graph_pass.cpp"],
  hdrs = ["render_graph.h", "render_graph_pass.h"],
  copts = [],
  deps = [
    "//:renderer",
  ],
  visibility = ["//visibility:public"],
)
