cc_library(
  name = "common",
  srcs = [
    "util.cpp",
    "camera_controller.cpp"
  ],
  hdrs = [
    "util.h",
    "camera_controller.h"
  ],
  deps = [
    "@glfw//:glfw",
    "@glm//:glm",
    "@gli//:gli",
    "//RenderAPI",
    "//third_party/ktx",
  ],
  visibility = ["//visibility:public"],
)