cc_library(
  name = "RenderAPI",
  hdrs = [
    "include/RenderAPI/RenderAPI.h",
    "include/RenderAPI/RenderAPI_texture.h",
    "include/RenderAPI/RenderAPI_pipelines.h",
  ],
  srcs = [
    "RenderAPI.cpp",
  ],
  includes = [
    "include"
  ],
  visibility = ["//visibility:public"],
)
