cc_library(
  name = "renderer",
  hdrs = [
    "include/renderer/renderer.h",
    "include/renderer/renderer_texture.h",
    "include/renderer/renderer_pipelines.h",
  ],
  srcs = [
    "renderer.cpp",
  ],
  includes = [
    "include"
  ],
  visibility = ["//visibility:public"],
)
