cc_library(
  name = "RenderUtils",
  hdrs = [
    "include/RenderUtils/BufferedDescriptorSet.h",
    "include/RenderUtils/BufferedBuffer.h",
  ],
  srcs = [
    "src/BufferedDescriptorSet.cpp",
    "src/BufferedBuffer.cpp",
  ],
  includes = [
    "include"
  ],
  deps = [
    "//:RenderAPI",
  ],
  visibility = ["//visibility:public"],
)
