cc_library(
  name = "RenderUtils",
  hdrs = [
    "include/RenderUtils/buffered_descriptor_set.h",
  ],
  srcs = [
    "src/buffered_descriptor_set.cpp"
  ],
  includes = [
    "include"
  ],
  deps = [
    "//:RenderAPI",
  ],
  visibility = ["//visibility:public"],
)
