cc_library(
  name = "generational",
  srcs = [
    "generational.cpp"
  ],
  hdrs = [
    "generational.h"
  ],
  copts = [],
  visibility = ["//visibility:public"],
)

cc_library(
  name = "generational_vector",
  hdrs = [
    "generational_vector.h"
  ],
  deps = [
    ":generational",
  ],
  visibility = ["//visibility:public"],
)